### ISSUE TITLE
Fix Network Nodes Editor compatibility issue

### ISSUE THREAD

**Issue by bloodypenguin** [AJ3D/Ploppable-RICO#6]
For some reason Ploppable RICO breaks Network Nodes Editor' tool. It probably breaks other custom tool as well but I got most comments for that mod.

**Comment by clausthaler-devel** [comment]
Thanks for notifying, but you as a developer should know that this is not a very helpful ticket. 
How does the error manifest itself? How to reproduce the issue, etc.

**Comment by AJ3D** [comment]
You mentioned is has something to do with the tool panel?

I wrote that from code that I read in GeneratedScrollPanel. 

I didn't use the GeneratedScrollPanel object like the props mod does because the category sorting didn't work. Perhaps there is a way around this, and my crappy panel object could be replaced?

**Comment by bloodypenguin** [comment]
@AJ3D I never mentioned GeneratedScrollPanel. But this looks suspicious:
https://github.com/AJ3D/Ploppable-RICO/blob/master/PloppableRCI/GUI/PloppableTool.cs#L55

@clausthaler-devel Sorry, I thought that was a well known issue :) When Ploppable RICO is enabled, Shift+N key combo of Network Nodes Editor doesn't engage its tool.

**Comment by AJ3D** [comment]
FIxed! 

I added PloppableTool to a game object, rather than ToolControler. Both work fine together now. 

Thanks for pointing out the troublesome code.
